# Generated by Django 6.0.4 on 2026-05-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alfajor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='alfajores/'),
        ),
    ]
