# Generated by Django 6.0.4 on 2026-05-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alfajor_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='alfajor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
